name: ${PROJECT_NAME}
services:
  rails:
    build:
      context: .
      dockerfile: ./docker/rails7.dockerfile
    container_name: ${PROJECT_NAME}_app
    command: bash -c "bundle install && rails s -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app
    ports:
      - "${RAILS_PORT}:3000"
    depends_on:
      - db
      - elasticsearch
    environment:
      DATABASE_URL: "${DB_ADAPTER}://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_DATABASE}"
      ELASTICSEARCH_URL: "http://${ES_HOST}:${ES_CONTAINER_PORT}"
    networks:
      - default

  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${DB_PORT}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - default

  pma:
    image: phpmyadmin:5.1
    container_name: ${PROJECT_NAME}_pma
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}
    ports:
      - "${PMA_PORT}:80"
    networks:
      - default
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.13
    container_name: ${PROJECT_NAME}_es
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false

    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "${ES_PORT}:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - default

networks:
  default:
    name: ${PROJECT_NAME}_railsnet
    driver: bridge
volumes:
  db_data:
  es_data: